module.exports = (sequelize, DataTypes) => {
    /* sequelize.define(A, B, C)
            argument A: name of table
            argument B: column names with attributes as objects
            argument C: table options
                timestamps: true => Sequelize adds createdAt and updatedAt columns
                paranoid: true => only useable if timestamps is true, adds deletedAt column,
                                    when row is deleted, instead of actually deleting, inserts timestamp of deletion command
                                    (only rows with null value for deletedAt column are detected!)
                underscored => changes the names of the columns generated by Sequelize into snake case
                                (ex) updatedAt => updated_at_
                tableName => used to designate a specific table name,
                                default, Sequelize takes argument A of sequelize.define() in plural form as the table name
     */
    return sequelize.define('user', {
        name: {
            type: DataTypes.STRING(20),
            allowNull: false,
            unique: true,
        },
        age: {
            type: DataTypes.INTEGER.UNSIGNED,
            allowNull: false,
        },
        married: {
            type: DataTypes.BOOLEAN,
            allowNull: false,
        },
        comment: {
            type: DataTypes.TEXT,
            allowNull: true,
        },
        created_at: {
            type: DataTypes.DATE,
            allowNull: false,
            defaultValue: DataTypes.NOW,
        },
    }), {
        timestamps: false,
    };
};